services:
  nginx:
    build:
      context: .
      dockerfile: ./Backend/nginx/Dockerfile
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8000:8000"
    volumes:
      - ./Frontend:/usr/share/nginx/html
    depends_on:
      - spa
      - pong
    env_file:
      - .env
    networks:
      - pong-network
      - spa-network
    container_name: nginx

  spa:
    build:
      context: .
      dockerfile: ./Backend/spa/Dockerfile
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./Backend/spa:/usr/src/app/Backend
      - ./Frontend:/usr/src/app/Frontend
    networks:
      - spa-network
      - pong-network
    depends_on:
      - pong
    container_name: spa
    env_file:
      - .env
    ports:
      - "3000:3000"

  pong:
    build:
      context: .
      dockerfile: ./Backend/pong/Dockerfile 
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    networks:
      - spa-network
      - pong-network
    container_name: pong
    env_file:
      - .env
    restart: "no"
    ports:
      - "4000:4000"

  users:
    build:
      context: .
      dockerfile: ./Backend/Users/Dockerfile
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./Backend/Users:/usr/src/app/Backend
      - sqlite_data:/usr/src/app/dataBase
    networks:
      - spa-network
    container_name: users
    env_file:
      - .env
    ports:
      - "5000:5000"

networks:
  spa-network:
    driver: bridge
  pong-network:
    driver: bridge

volumes:
  sqlite_data: