services:
  nginx:
    build:
      context: .
      dockerfile: ./Backend/nginx/Dockerfile
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8000:8000"
    volumes:
      - ./Frontend:/usr/share/nginx/html
    depends_on:
      - spa
    env_file:
      - .env
    networks:
      - spa-network
    container_name: nginx

  spa:
    build:
      context: .
      dockerfile: ./Backend/spa/Dockerfile
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./Backend/spa:/usr/src/app/Backend
      - ./Frontend:/usr/src/app/Frontend
    networks:
      - spa-network
    container_name: spa
    env_file:
      - .env
  
  users:
    build:
      context: .
      dockerfile: ./Backend/Users/Dockerfile
      args: 
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./Backend/Users:/usr/src/app/Backend
      - sqlite_data:/usr/src/app/dataBase
    networks:
      - spa-network
    container_name: users
    env_file:
      - .env
networks:
  spa-network:
    driver: bridge

volumes:
  sqlite_data: