services:
  nginx:
    build:
      context: .
      dockerfile: ./Backend/nginx/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fastify
    networks:
      - app-network
    container_name: nginx

  fastify:
    build:
      context: .
      dockerfile: ./Backend/fastify/Dockerfile
      args: 
        USER_ID: ${USER_ID}   # Utilisateur de l'hôte (modifiez si nécessaire)
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./Backend/fastify:/usr/src/app/Backend
      - ./Frontend:/usr/src/app/Frontend
      - sqlite_data:/usr/src/app/dataBase
    networks:
      - app-network
    container_name: fastify
    env_file:
      - .env
networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data: