services:
  nginx:
    build:
      context: .
      dockerfile: ./Backend/nginx/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fastify
    networks:
      - app-network
    container_name: nginx

  fastify:
    build:
      context: .
      dockerfile: ./Backend/fastify/Dockerfile
    volumes:
      - ./Backend/fastify:/usr/src/app/Backend
      - ./Frontend:/usr/src/app/Frontend
    networks:
      - app-network
    container_name: fastify

networks:
  app-network:
    driver: bridge