global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    static_configs:
      - targets: ['localhost:9090']
    tls_config:
      ca_file: /etc/prometheus/certs/ca.crt
      cert_file: /etc/prometheus/certs/prometheus.crt
      key_file: /etc/prometheus/certs/prometheus.key
      insecure_skip_verify: false

  - job_name: 'nginx-exporter'
    scheme: https
    static_configs:
      - targets: ['nginx-exporter:9113']
    tls_config:
      ca_file: /etc/prometheus/certs/ca.crt
      cert_file: /etc/exporter/certs/exporter.crt
      key_file: /etc/exporter/certs/exporter.key
      insecure_skip_verify: false
